### ISSUE TITLE
Random Crashing

### ISSUE THREAD

**Issue by CircularSwarm** [BrandonDyer64/Manbaby#17]
The bot randomly stops playing music and locks up. This happened once after I skipped a song and once after changing songs without me skipping, implying it is an issue with changing songs. 
I think this seems like something you know about, but I am apparently being told to write it up nonetheless.

**Comment by CircularSwarm** [comment]
Megadynamite: ;play
Megadynamite: ;help
Megadynamite: ;leave
null left Megadynamite General
TypeError: Cannot read property 'encode' of null
    at StreamDispatcher.sendBuffer (/root/ViciousManbaby/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:133:56)
    at StreamDispatcher.process (/root/ViciousManbaby/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:243:14)
    at Socket.stream.once (/root/ViciousManbaby/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:324:12)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:537:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
TypeError: Cannot read property 'send' of null
    at StreamDispatcher.sendPacket (/root/ViciousManbaby/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:147:47)
    at StreamDispatcher.sendBuffer (/root/ViciousManbaby/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:135:10)
    at StreamDispatcher.process (/root/ViciousManbaby/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:243:14)
    at Socket.stream.once (/root/ViciousManbaby/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:324:12)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:537:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
